/**
 * OAuth Configuration
 * Loads OAuth credentials from runtime config file
 *
 * NOTE: In production, these credentials should be served from a secure backend
 * or OAuth proxy (Cloudflare Workers, Vercel Functions) to avoid exposing secrets.
 *
 * To configure:
 * 1. Copy .env.example to .env
 * 2. Add your OAuth credentials
 * 3. Run: npm run build:config
 */

// Import runtime config (generated from .env by build script)
// This is a JavaScript module generated by build-config.js
import { runtimeConfig as importedRuntimeConfig } from './runtime-config.js';

let runtimeConfig = importedRuntimeConfig || {};

console.log('[OAuth Config] Runtime config loaded successfully');

// GitHub OAuth Configuration
export const GITHUB_OAUTH_CONFIG = {
  clientId: runtimeConfig.github?.clientId || 'YOUR_GITHUB_CLIENT_ID',
  clientSecret: runtimeConfig.github?.clientSecret || 'YOUR_GITHUB_CLIENT_SECRET',
  authUrl: 'https://github.com/login/oauth/authorize',
  tokenUrl: 'https://github.com/login/oauth/access_token',
  apiUrl: 'https://api.github.com',
  scopes: ['repo', 'project', 'read:user']
};

// Google OAuth Configuration (Phase 3)
export const GOOGLE_OAUTH_CONFIG = {
  clientId: runtimeConfig.google?.clientId || '',
  clientSecret: runtimeConfig.google?.clientSecret || '',
  authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
  tokenUrl: 'https://oauth2.googleapis.com/token',
  scopes: ['https://www.googleapis.com/auth/userinfo.email']
};

// Notion OAuth Configuration (Phase 5)
export const NOTION_OAUTH_CONFIG = {
  clientId: runtimeConfig.notion?.clientId || '',
  clientSecret: runtimeConfig.notion?.clientSecret || '',
  authUrl: 'https://api.notion.com/v1/oauth/authorize',
  tokenUrl: 'https://api.notion.com/v1/oauth/token',
  scopes: []
};

/**
 * Validate that required OAuth config is present
 * @param {string} provider - Provider name (github, google, notion)
 * @returns {boolean} True if config is valid
 */
export function validateOAuthConfig(provider) {
  const configs = {
    github: GITHUB_OAUTH_CONFIG,
    google: GOOGLE_OAUTH_CONFIG,
    notion: NOTION_OAUTH_CONFIG
  };

  const config = configs[provider];
  if (!config) {
    console.error(`[OAuth Config] Unknown provider: ${provider}`);
    return false;
  }

  if (!config.clientId || config.clientId.startsWith('YOUR_')) {
    console.error(`[OAuth Config] Missing ${provider} client ID`);
    return false;
  }

  if (!config.clientSecret || config.clientSecret.startsWith('YOUR_')) {
    console.error(`[OAuth Config] Missing ${provider} client secret`);
    return false;
  }

  return true;
}
