/**
 * Build Configuration Script
 * Loads environment variables and creates a runtime config file
 *
 * Usage: node scripts/build-config.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env file
function loadEnv() {
  const envPath = path.join(__dirname, '..', '.env');

  if (!fs.existsSync(envPath)) {
    console.warn('⚠️  No .env file found. Using .env.example as template.');
    console.warn('   Copy .env.example to .env and add your credentials.');
    return {};
  }

  const envContent = fs.readFileSync(envPath, 'utf-8');
  const env = {};

  envContent.split('\n').forEach(line => {
    // Skip comments and empty lines
    if (line.trim().startsWith('#') || !line.trim()) return;

    const [key, ...valueParts] = line.split('=');
    const value = valueParts.join('=').trim();

    if (key && value) {
      env[key.trim()] = value;
    }
  });

  return env;
}

// Generate runtime config
function generateConfig() {
  const env = loadEnv();

  console.log('Loaded env:', env);

  const config = {
    github: {
      clientId: env.GITHUB_CLIENT_ID || 'YOUR_GITHUB_CLIENT_ID',
      clientSecret: env.GITHUB_CLIENT_SECRET || 'YOUR_GITHUB_CLIENT_SECRET'
    },
    google: {
      clientId: env.GOOGLE_CLIENT_ID || '',
      clientSecret: env.GOOGLE_CLIENT_SECRET || ''
    },
    notion: {
      clientId: env.NOTION_CLIENT_ID || '',
      clientSecret: env.NOTION_CLIENT_SECRET || ''
    },
    zai: {
      apiKey: env.ZAI_API_KEY || 'your_zai_api_key_here'
    },
    openrouter: {
      apiKey: env.OPENROUTER_API_KEY || 'your_openrouter_api_key_here'
    },
    claude: {
      apiKey: env.ANTHROPIC_API_KEY || 'your_anthropic_api_key_here'
    }
  };

  // Validate GitHub config
  const hasGitHubConfig = config.github.clientId !== 'YOUR_GITHUB_CLIENT_ID' &&
                          config.github.clientSecret !== 'YOUR_GITHUB_CLIENT_SECRET';

  if (!hasGitHubConfig) {
    console.warn('⚠️  GitHub OAuth credentials not configured!');
    console.warn('   GitHub issue creation will not be available.');
    console.warn('   To enable: Copy .env.example to .env and add your GitHub credentials.');
  }

  // Check vision providers
  const hasZai = config.zai.apiKey !== 'your_zai_api_key_here';
  const hasOpenRouter = config.openrouter.apiKey !== 'your_openrouter_api_key_here';
  const hasClaude = config.claude.apiKey !== 'your_anthropic_api_key_here';

  if (!hasZai && !hasOpenRouter && !hasClaude) {
    console.warn('⚠️  No vision provider API keys configured!');
    console.warn('   Vision analysis features will not be available.');
    console.warn('   To enable: Add at least one of ZAI_API_KEY, OPENROUTER_API_KEY, or ANTHROPIC_API_KEY to .env');
  } else {
    const providers = [];
    if (hasZai) providers.push('Zai (Zhipu AI)');
    if (hasOpenRouter) providers.push('OpenRouter');
    if (hasClaude) providers.push('Claude Code (Anthropic)');
    console.log(`✅ Vision providers configured: ${providers.join(', ')}`);
  }

  return config;
}

// Write config to file
function writeConfig(config) {
  const outputPath = path.join(__dirname, '..', 'src', 'config', 'runtime-config.js');

  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Generate JavaScript module instead of JSON for better Chrome extension compatibility
  const jsContent = `/**
 * Runtime OAuth Configuration
 * Auto-generated from .env by build-config.js
 * DO NOT EDIT THIS FILE MANUALLY
 */

export const runtimeConfig = ${JSON.stringify(config, null, 2)};
`;

  fs.writeFileSync(outputPath, jsContent);
  console.log('✅ Runtime config generated successfully!');
  console.log(`   File: ${outputPath}`);
}

// Main
try {
  const config = generateConfig();
  writeConfig(config);
} catch (error) {
  console.error('❌ Error generating config:', error.message);
  process.exit(1);
}
